
export type FontOption = {
  value: string;
  label: string;
  fontFamily: string;
  weight: string | number;
  size: number | string; // Base size for body text, title will be a multiple of this
  lineHeight: number | string; // This should be a multiplier, e.g., 1.4
};


export const fontOptions: FontOption[] = [
    { value: 'amatic-sc', label: 'Amatic SC', fontFamily: "'Amatic SC', cursive", weight: '700', size: 58, lineHeight: 1.3 },
    { value: 'anton', label: 'Anton', fontFamily: "'Anton', sans-serif", weight: '400', size: 58, lineHeight: 1.3 },
    { value: 'arima', label: 'Arima', fontFamily: "'Arima', cursive", weight: '700', size: 50, lineHeight: 1.4 },
    { value: 'arsenal', label: 'Arsenal', fontFamily: "'Arsenal', sans-serif", weight: '400', size: 52, lineHeight: 1.4 },
    { value: 'beau-rivage', label: 'Beau Rivage', fontFamily: "'Beau Rivage', cursive", weight: '400', size: 56, lineHeight: 1.3 },
    { value: 'bebas-neue', label: 'Bebas Neue', fontFamily: "'Bebas Neue', sans-serif", weight: '400', size: 56, lineHeight: 1.3 },
    { value: 'bree-serif', label: 'Bree Serif', fontFamily: "'Bree Serif', serif", weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'carattere', label: 'Carattere', fontFamily: "'Carattere', cursive", weight: '400', size: 60, lineHeight: 1.3 },
    { value: 'catamaran', label: 'Catamaran', fontFamily: "'Catamaran', sans-serif", weight: '700', size: 50, lineHeight: 1.4 },
    { value: 'cherry-bomb-one', label: 'Cherry Bomb One', fontFamily: "'Cherry Bomb One', cursive", weight: '400', size: 48, lineHeight: 1.4 },
    { value: 'coiny', label: 'Coiny', fontFamily: "'Coiny', cursive", weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'cutive', label: 'Cutive', fontFamily: "'Cutive', serif", weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'dosis', label: 'Dosis', fontFamily: "'Dosis', sans-serif", weight: '700', size: 52, lineHeight: 1.3 },
    { value: 'duru-sans', label: 'Duru Sans', fontFamily: "'Duru Sans', sans-serif", weight: '400', size: 48, lineHeight: 1.4 },
    { value: 'ephesis', label: 'Ephesis', fontFamily: "'Ephesis', cursive", weight: '400', size: 62, lineHeight: 1.3 },
    { value: 'exo-2', label: 'Exo 2', fontFamily: "'Exo 2', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'great-vibes', label: 'Great Vibes', fontFamily: "'Great Vibes', cursive", weight: '400', size: 60, lineHeight: 1.3 },
    { value: 'ibm-plex-sans', label: 'IBM Plex Sans', fontFamily: "'IBM Plex Sans', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'indie-flower', label: 'Indie Flower', fontFamily: "'Indie Flower', cursive", weight: '400', size: 52, lineHeight: 1.4 },
    { value: 'instrument-serif', label: 'Instrument Serif', fontFamily: "'Instrument Serif', serif", weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'inter', label: 'Inter', fontFamily: "'Inter', sans-serif", weight: '600', size: 52, lineHeight: 1.4 },
    { value: 'italianno', label: 'Italianno', fontFamily: "'Italianno', cursive", weight: '400', size: 60, lineHeight: 1.3 },
    { value: 'josefin-sans', label: 'Josefin Sans', fontFamily: "'Josefin Sans', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'kablammo', label: 'Kablammo', fontFamily: "'Kablammo', cursive", weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'lato', label: 'Lato', fontFamily: "'Lato', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'lexend-deca', label: 'Lexend Deca', fontFamily: "'Lexend Deca', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'licorice', label: 'Licorice', fontFamily: "'Licorice', cursive", weight: '400', size: 62, lineHeight: 1.3 },
    { value: 'lobster', label: 'Lobster', fontFamily: "'Lobster', cursive", weight: '400', size: 54, lineHeight: 1.4 },
    { value: 'luckiest-guy', label: 'Luckiest Guy', fontFamily: "'Luckiest Guy', cursive", weight: '400', size: 'calc(20px + 8vh)', lineHeight: 1.2 },
    { value: 'mea-culpa', label: 'Mea Culpa', fontFamily: "'Mea Culpa', cursive", weight: '400', size: 58, lineHeight: 1.3 },
    { value: 'montez', label: 'Montez', fontFamily: "'Montez', cursive", weight: '400', size: 58, lineHeight: 1.3 },
    { value: 'neonderthaw', label: 'Neonderthaw', fontFamily: "'Neonderthaw', cursive", weight: '400', size: 95, lineHeight: 1.4 },
    { value: 'niconne', label: 'Niconne', fontFamily: "'Niconne', cursive", weight: '400', size: 'calc(20px + 6vh)', lineHeight: 1.5 },
    { value: 'norican', label: 'Norican', fontFamily: "'Norican', cursive", weight: '400', size: 55, lineHeight: 1.4 },
    { value: 'noto-sans-display', label: 'Noto Sans Display', fontFamily: "'Noto Sans Display', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'nunito', label: 'Nunito', fontFamily: "'Nunito', sans-serif", weight: '700', size: 50, lineHeight: 1.4 },
    { value: 'open-sans', label: 'Open Sans', fontFamily: "'Open Sans', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'oswald', label: 'Oswald', fontFamily: "'Oswald', sans-serif", weight: '700', size: 46, lineHeight: 1.4 },
    { value: 'oxygen', label: 'Oxygen', fontFamily: "'Oxygen', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'pattaya', label: 'Pattaya', fontFamily: "'Pattaya', sans-serif", weight: '400', size: 52, lineHeight: 1.4 },
    { value: 'playfair-display', label: 'Playfair Display', fontFamily: "'Playfair Display', serif", weight: '700', size: 52, lineHeight: 1.4 },
    { value: 'plus-jakarta-sans', label: 'Plus Jakarta Sans', fontFamily: "'Plus Jakarta Sans', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'poppins', label: 'Poppins', fontFamily: "'Poppins', sans-serif", weight: '700', size: 50, lineHeight: 1.4 },
    { value: 'poiret-one', label: 'Poiret One', fontFamily: "'Poiret One', sans-serif", weight: '400', size: 52, lineHeight: 1.3 },
    { value: 'pt-sans', label: 'PT Sans', fontFamily: "'PT Sans', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'raleway', label: 'Raleway', fontFamily: "'Raleway', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'red-hat-display', label: 'Red Hat Display', fontFamily: "'Red Hat Display', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'ribeye-marrow', label: 'Ribeye Marrow', fontFamily: "'Ribeye Marrow', cursive", weight: '400', size: 48, lineHeight: 1.4 },
    { value: 'roboto', label: 'Roboto', fontFamily: "'Roboto', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'roboto-slab', label: 'Roboto Slab', fontFamily: "'Roboto Slab', serif", weight: '700', size: 46, lineHeight: 1.4 },
    { value: 'romanesco', label: 'Romanesco', fontFamily: "'Romanesco', cursive", weight: '400', size: 60, lineHeight: 1.3 },
    { value: 'sacramento', label: 'Sacramento', fontFamily: "'Sacramento', cursive", weight: '400', size: 58, lineHeight: 1.6 },
    { value: 'sansita', label: 'Sansita', fontFamily: "'Sansita', sans-serif", weight: '700', size: 50, lineHeight: 1.4 },
    { value: 'shadows-into-light', label: 'Shadows Into Light', fontFamily: "'Shadows Into Light', cursive", weight: '400', size: 56, lineHeight: 1.5 },
    { value: 'slabo-27px', label: 'Slabo 27px', fontFamily: "'Slabo 27px', serif", weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'smooch-sans', label: 'Smooch Sans', fontFamily: "'Smooch Sans', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'source-sans-3', label: 'Source Sans 3', fontFamily: "'Source Sans 3', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'special-elite', label: 'Special Elite', fontFamily: "'Special Elite', cursive", weight: '400', size: 48, lineHeight: 1.4 },
    { value: 'style-script', label: 'Style Script', fontFamily: "'Style Script', cursive", weight: '400', size: 58, lineHeight: 1.3 },
    { value: 'syne', label: 'Syne', fontFamily: "'Syne', sans-serif", weight: '700', size: 46, lineHeight: 1.4 },
    { value: 'tenor-sans', label: 'Tenor Sans', fontFamily: "'Tenor Sans', sans-serif", weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'tilt-neon', label: 'Tilt Neon', fontFamily: "'Tilt Neon', sans-serif", weight: '400', size: 'calc(15px + 8vh)', lineHeight: 1.4 },
    { value: 'titillium-web', label: 'Titillium Web', fontFamily: "'Titillium Web', sans-serif", weight: '700', size: 46, lineHeight: 1.4 },
    { value: 'ubuntu', label: 'Ubuntu', fontFamily: "'Ubuntu', sans-serif", weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'updock', label: 'Updock', fontFamily: "'Updock', cursive", weight: '400', size: 58, lineHeight: 1.3 },
    { value: 'windsong', label: 'WindSong', fontFamily: "'WindSong', cursive", weight: '400', size: 62, lineHeight: 1.3 },
    { value: 'yesteryear', label: 'Yesteryear', fontFamily: "'Yesteryear', cursive", weight: '400', size: 58, lineHeight: 1.3 },
];

    