
export const imageTemplates = [
  { name: "bg-clouds", imageUrl: "https://i.ibb.co/KjNBYSMK/bg-clouds.jpg" },
  { name: "bg-pink-Dock", imageUrl: "https://i.ibb.co/gFTNhzNw/bg-pink-Dock.jpg" },
  { name: "lightWave", imageUrl: "https://i.ibb.co/G44Pqbxw/bg2.jpg" },
  { name: "bg-night-Station", imageUrl: "https://i.ibb.co/fYCwYK0L/bg-night-Station.jpg" },
  { name: "bg-casette", imageUrl: "https://i.ibb.co/7JRjdmHF/bg-Casette.jpg" },
  { name: "bg-grass", imageUrl: "https://i.ibb.co/6c3XD0xk/bg-grass.jpg" },
  { name: "bgImage-28", imageUrl: "https://i.ibb.co/1jZdJPV/28.jpg" },
  { name: "square", imageUrl: "https://i.ibb.co/5hRnrGqX/25.jpg" },
  { name: "twoLines", imageUrl: "https://i.ibb.co/cSNxXVn5/1.jpg" },
  { name: "cardboard paper", imageUrl: "https://i.ibb.co/21RBM4zK/2.jpg" },
  { name: "whiteWindow", imageUrl: "https://i.ibb.co/fG4jwVJk/3.jpg" },
  { name: "watercolorLines", imageUrl: "https://i.ibb.co/DmLYr9c/4.jpg" },
  { name: "watercolor-branch", imageUrl: "https://i.ibb.co/NngKdzDr/5.jpg" },
  { name: "white-fabric", imageUrl: "https://i.ibb.co/kVJS28vc/6.jpg" },
  { name: "marble", imageUrl: "https://i.ibb.co/DDZ3y2Lk/7.jpg" },
  { name: "wallShadow1", imageUrl: "https://i.ibb.co/qMsVxTVP/8.jpg" },
  { name: "wallShadow2", imageUrl: "https://i.ibb.co/dwpMznqZ/9.jpg" },
  { name: "wallShadow3", imageUrl: "https://i.ibb.co/20LWKfg2/10.jpg" },
  { name: "daisy", imageUrl: "https://i.ibb.co/0pPsjhzm/11.jpg" },
  { name: "watercolor-branch2", imageUrl: "https://i.ibb.co/60jqfPL0/12.jpg" },
  { name: "goldFrame-white", imageUrl: "https://i.ibb.co/prMd6Jrx/13.jpg" },
  { name: "goldFrame-black", imageUrl: "https://i.ibb.co/HTRtS40v/14.jpg" },
  { name: "bgImage-15", imageUrl: "https://i.ibb.co/kVzt8JY3/15.jpg" },
  { name: "bgImage-16", imageUrl: "https://i.ibb.co/DqpzHmd/16.jpg" },
  { name: "bgImage-17", imageUrl: "https://i.ibb.co/pBgc28z1/17.jpg" },
  { name: "bgImage-18", imageUrl: "https://i.ibb.co/KzSvH8MX/18.jpg" },
  { name: "bgImage-19", imageUrl: "https://i.ibb.co/Qj8wydws/19.jpg" },
  { name: "bgImage-20", imageUrl: "https://i.ibb.co/nsNShDnK/20.jpg" },
  { name: "bgImage-21", imageUrl: "https://i.ibb.co/xq1cZcmL/21.jpg" },
  { name: "bgImage-22", imageUrl: "https://i.ibb.co/ym0R346S/22.jpg" },
  { name: "bgImage-23", imageUrl: "https://i.ibb.co/1Jtzn1X6/23.jpg" },
  { name: "bgImage-24", imageUrl: "https://i.ibb.co/395BJVBs/24.jpg" },
  { name: "paperclip-rose", imageUrl: "https://i.ibb.co/W4nLHRZd/27.jpg" }
];
