
export const imageTemplates = [
  { name: "bg-clouds", imageUrl: "https://i.ibb.co/KjNBYSMK/bg-clouds.jpg" },
  { name: "bg-pink-Dock", imageUrl: "https://i.ibb.co/gFTNhzN/bg-pink-Dock.jpg" },
  { name: "lightWave", imageUrl: "https://i.ibb.co/44Pqbxw/bg2.jpg" },
  { name: "bg-night-Station", imageUrl: "https://i.ibb.co/fYCwYK0/bg-night-Station.jpg" },
  { name: "bg-wall", imageUrl: "https://i.ibb.co/Txg2jcJ/bg.jpg" },
  { name: "bg-casette", imageUrl: "https://i.ibb.co/7JRjdmH/bg-Casette.jpg" },
  { name: "bg-grass", imageUrl: "https://i.ibb.co/6c3XD0x/bg-grass.jpg" },
  { name: "bgImage-28", imageUrl: "https://i.ibb.co/jZdJPV/28.jpg" },
  { name: "square", imageUrl: "https://i.ibb.co/5hRnrGq/25.jpg" },
  { name: "twoLines", imageUrl: "https://i.ibb.co/cSNxXVn/1.jpg" },
  { name: "cardboard paper", imageUrl: "https://i.ibb.co/2RBM4zK/2.jpg" },
  { name: "whiteWindow", imageUrl: "https://i.ibb.co/G4jwVJk/3.jpg" },
  { name: "watercolorLines", imageUrl: "https://i.ibb.co/DmLYr9c/4.jpg" },
  { name: "watercolor-branch", imageUrl: "https://i.ibb.co/NngKdzDr/5.jpg" },
  { name: "white-fabric", imageUrl: "https://i.ibb.co/kVJS28v/6.jpg" },
  { name: "marble", imageUrl: "https://i.ibb.co/DDZ3y2L/7.jpg" },
  { name: "wallShadow1", imageUrl: "https://i.ibb.co/qMsVxTV/8.jpg" },
  { name: "wallShadow2", imageUrl: "https://i.ibb.co/dwpMznq/9.jpg" },
  { name: "wallShadow3", imageUrl: "https://i.ibb.co/2LWKfg2/10.jpg" },
  { name: "daisy", imageUrl: "https://i.ibb.co/pPsjhzm/11.jpg" },
  { name: "watercolor-branch2", imageUrl: "https://i.ibb.co/60jqfPL/12.jpg" },
  { name: "goldFrame-white", imageUrl: "https://i.ibb.co/prMd6Jr/13.jpg" },
  { name: "goldFrame-black", imageUrl: "https://i.ibb.co/HTRtS40/14.jpg" },
  { name: "bgImage-15", imageUrl: "https://i.ibb.co/kVzt8JY/15.jpg" },
  { name: "bgImage-16", imageUrl: "https://i.ibb.co/DqpzHmd/16.jpg" },
  { name: "bgImage-17", imageUrl: "https://i.ibb.co/pBgc28z/17.jpg" },
  { name: "bgImage-18", imageUrl: "https://i.ibb.co/KzSvH8M/18.jpg" },
  { name: "bgImage-19", imageUrl: "https://i.ibb.co/Qj8wydw/19.jpg" },
  { name: "bgImage-20", imageUrl: "https://i.ibb.co/nsNShDn/20.jpg" },
  { name: "bgImage-21", imageUrl: "https://i.ibb.co/xq1cZcm/21.jpg" },
  { name: "bgImage-22", imageUrl: "https://i.ibb.co/ym0R346/22.jpg" },
  { name: "bgImage-23", imageUrl: "https://i.ibb.co/Jtzn1X6/23.jpg" },
  { name: "bgImage-24", imageUrl: "https://i.ibb.co/395BJVb/24.jpg" },
  { name: "paperclip-rose", imageUrl: "https://i.ibb.co/W4nLHRZ/27.jpg" }
];

    