
export type FontOption = {
  value: string;
  label: string;
  fontFamily: string;
  weight: string | number;
  size: number; // Base size for body text, title will be a multiple of this
  lineHeight: number; // This should be a multiplier, e.g., 1.4
};


export const fontOptions: FontOption[] = [
    { value: 'anton', label: 'Anton', fontFamily: 'Anton', weight: '400', size: 58, lineHeight: 1.3 },
    { value: 'arsenal', label: 'Arsenal', fontFamily: 'Arsenal', weight: '400', size: 52, lineHeight: 1.4 },
    { value: 'beau-rivage', label: 'Beau Rivage', fontFamily: 'Beau Rivage', weight: '400', size: 56, lineHeight: 1.3 },
    { value: 'bree-serif', label: 'Bree Serif', fontFamily: 'Bree Serif', weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'carattere', label: 'Carattere', fontFamily: 'Carattere', weight: '400', size: 60, lineHeight: 1.3 },
    { value: 'catamaran', label: 'Catamaran', fontFamily: 'Catamaran', weight: '700', size: 50, lineHeight: 1.4 },
    { value: 'cherry-bomb-one', label: 'Cherry Bomb One', fontFamily: 'Cherry Bomb One', weight: '400', size: 48, lineHeight: 1.4 },
    { value: 'coiny', label: 'Coiny', fontFamily: 'Coiny', weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'dosis', label: 'Dosis', fontFamily: 'Dosis', weight: '700', size: 52, lineHeight: 1.3 },
    { value: 'duru-sans', label: 'Duru Sans', fontFamily: 'Duru Sans', weight: '400', size: 48, lineHeight: 1.4 },
    { value: 'ephesis', label: 'Ephesis', fontFamily: 'Ephesis', weight: '400', size: 62, lineHeight: 1.3 },
    { value: 'exo-2', label: 'Exo 2', fontFamily: 'Exo 2', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'faculty-glyphic', label: 'Faculty Glyphic', fontFamily: 'Faculty Glyphic', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'farro', label: 'Farro', fontFamily: 'Farro', weight: '700', size: 46, lineHeight: 1.4 },
    { value: 'fleur-de-leah', label: 'Fleur De Leah', fontFamily: 'Fleur De Leah', weight: '400', size: 54, lineHeight: 1.4 },
    { value: 'grand-hotel', label: 'Grand Hotel', fontFamily: 'Grand Hotel', weight: '400', size: 55, lineHeight: 1.4 },
    { value: 'ibm-plex-sans', label: 'IBM Plex Sans', fontFamily: 'IBM Plex Sans', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'inter', label: 'Inter', fontFamily: 'Inter', weight: '600', size: 52, lineHeight: 1.4 },
    { value: 'italianno', label: 'Italianno', fontFamily: 'Italianno', weight: '400', size: 60, lineHeight: 1.3 },
    { value: 'josefin-sans', label: 'Josefin Sans', fontFamily: 'Josefin Sans', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'kablammo', label: 'Kablammo', fontFamily: 'Kablammo', weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'lato', label: 'Lato', fontFamily: 'Lato', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'lexend-deca', label: 'Lexend Deca', fontFamily: 'Lexend Deca', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'licorice', label: 'Licorice', fontFamily: 'Licorice', weight: '400', size: 62, lineHeight: 1.3 },
    { value: 'lobster', label: 'Lobster', fontFamily: 'Lobster', weight: '400', size: 54, lineHeight: 1.4 },
    { value: 'luckiest-guy', label: 'Luckiest Guy', fontFamily: 'Luckiest Guy', weight: '400', size: 48, lineHeight: 1.2 },
    { value: 'mea-culpa', label: 'Mea Culpa', fontFamily: 'Mea Culpa', weight: '400', size: 58, lineHeight: 1.3 },
    { value: 'montez', label: 'Montez', fontFamily: 'Montez', weight: '400', size: 58, lineHeight: 1.3 },
    { value: 'neonderthaw', label: 'Neonderthaw', fontFamily: 'Neonderthaw', weight: '400', size: 95, lineHeight: 1.4 },
    { value: 'niconne', label: 'Niconne', fontFamily: 'Niconne', weight: '400', size: 60, lineHeight: 1.5 },
    { value: 'norican', label: 'Norican', fontFamily: 'Norican', weight: '400', size: 55, lineHeight: 1.4 },
    { value: 'noto-sans-display', label: 'Noto Sans Display', fontFamily: 'Noto Sans Display', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'nunito', label: 'Nunito', fontFamily: 'Nunito', weight: '700', size: 50, lineHeight: 1.4 },
    { value: 'open-sans', label: 'Open Sans', fontFamily: 'Open Sans', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'oswald', label: 'Oswald', fontFamily: 'Oswald', weight: '700', size: 46, lineHeight: 1.4 },
    { value: 'oxygen', label: 'Oxygen', fontFamily: 'Oxygen', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'pattaya', label: 'Pattaya', fontFamily: 'Pattaya', weight: '400', size: 52, lineHeight: 1.4 },
    { value: 'playfair-display', label: 'Playfair Display', fontFamily: 'Playfair Display', weight: '700', size: 52, lineHeight: 1.4 },
    { value: 'playwrite-england-joined', label: 'Playwrite England Joined', fontFamily: 'Playwrite England Joined', weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'playwrite-france-moderne', label: 'Playwrite France Moderne', fontFamily: 'Playwrite France Moderne', weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'playwrite-usa-modern', label: 'Playwrite USA Modern', fontFamily: 'Playwrite USA Modern', weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'plus-jakarta-sans', label: 'Plus Jakarta Sans', fontFamily: 'Plus Jakarta Sans', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'poppins', label: 'Poppins', fontFamily: 'Poppins', weight: '700', size: 50, lineHeight: 1.4 },
    { value: 'poiret-one', label: 'Poiret One', fontFamily: 'Poiret One', weight: '400', size: 52, lineHeight: 1.3 },
    { value: 'pt-sans', label: 'PT Sans', fontFamily: 'PT Sans', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'raleway', label: 'Raleway', fontFamily: 'Raleway', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'red-hat-display', label: 'Red Hat Display', fontFamily: 'Red Hat Display', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'ribeye-marrow', label: 'Ribeye Marrow', fontFamily: 'Ribeye Marrow', weight: '400', size: 48, lineHeight: 1.4 },
    { value: 'roboto', label: 'Roboto', fontFamily: 'Roboto', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'roboto-slab', label: 'Roboto Slab', fontFamily: 'Roboto Slab', weight: '700', size: 46, lineHeight: 1.4 },
    { value: 'romanesco', label: 'Romanesco', fontFamily: 'Romanesco', weight: '400', size: 60, lineHeight: 1.3 },
    { value: 'sansita', label: 'Sansita', fontFamily: 'Sansita', weight: '700', size: 50, lineHeight: 1.4 },
    { value: 'slabo-27px', label: 'Slabo 27px', fontFamily: 'Slabo 27px', weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'smooch-sans', label: 'Smooch Sans', fontFamily: 'Smooch Sans', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'sour-gummy', label: 'Sour Gummy', fontFamily: 'Sour Gummy', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'source-sans-3', label: 'Source Sans 3', fontFamily: 'Source Sans 3', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'special-elite', label: 'Special Elite', fontFamily: 'Special Elite', weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'style-script', label: 'Style Script', fontFamily: 'Style Script', weight: '400', size: 58, lineHeight: 1.3 },
    { value: 'syne', label: 'Syne', fontFamily: 'Syne', weight: '700', size: 46, lineHeight: 1.4 },
    { value: 'tenor-sans', label: 'Tenor Sans', fontFamily: 'Tenor Sans', weight: '400', size: 50, lineHeight: 1.4 },
    { value: 'tilt-neon', label: 'Tilt Neon', fontFamily: 'Tilt Neon', weight: '400', size: 48, lineHeight: 1.4 },
    { value: 'titillium-web', label: 'Titillium Web', fontFamily: 'Titillium Web', weight: '700', size: 46, lineHeight: 1.4 },
    { value: 'ubuntu', label: 'Ubuntu', fontFamily: 'Ubuntu', weight: '700', size: 48, lineHeight: 1.4 },
    { value: 'updock', label: 'Updock', fontFamily: 'Updock', weight: '400', size: 58, lineHeight: 1.3 },
    { value: 'windsong', label: 'WindSong', fontFamily: 'WindSong', weight: '400', size: 62, lineHeight: 1.3 },
    { value: 'yesteryear', label: 'Yesteryear', fontFamily: 'Yesteryear', weight: '400', size: 58, lineHeight: 1.3 },
];
